# app/types/gql/queries/get-hero.gql

query GetHomeHero {
	allHome {
		_id
		hero {
			title {
				fr
				en
			}
			subtitle {
				fr
				en
			}
			applyMyProject {
				fr
				en
			}
			reserveStrategyCall {
				fr
				en
			}
			link
		}
	}
}